#ifndef CONCORD_AUDIOSYNTH_H
#define CONCORD_AUDIOSYNTH_H

#include "Concord/CExport.h"
#include "audio/synth/AudioBuiltInSound.h"

#include <cstdint>
#include <vector>

namespace Concord::Audio {

/** Oscillator shapes available to the built-in synthesizer. */
enum class AudioWaveform : std::uint8_t {
    Sine = 0,
    Square,
    Triangle,
    Saw,
    Noise,
};

/** ADSR-style envelope used when synthesizing a clip. */
struct AudioEnvelope {
    float attackSeconds = 0.01f;
    float decaySeconds = 0.05f;
    float sustainLevel = 0.8f;
    float releaseSeconds = 0.08f;
};

/** Plain-data procedural synthesis description. */
struct AudioSynthesisDesc {
    std::int32_t sampleRate = 48000;
    std::uint8_t channels = 1;
    float durationSeconds = 0.35f;
    float frequencyHz = 440.0f;
    float endFrequencyHz = 440.0f;
    float amplitude = 0.25f;
    float vibratoHz = 0.0f;
    float vibratoDepth = 0.0f;
    float tremoloHz = 0.0f;
    float tremoloDepth = 0.0f;
    std::uint32_t noiseSeed = 1;
    AudioWaveform waveform = AudioWaveform::Sine;
    AudioEnvelope envelope{};
};

/** CPU-side PCM buffer generated by the built-in synthesizer. */
struct AudioSynthBuffer {
    std::int32_t sampleRate = 48000;
    std::uint8_t channels = 1;
    std::vector<float> samples;
};

/** Built-in procedural audio generator. */
class CAUDIO_API AudioSynth {
public:
    static AudioSynthBuffer Generate(const AudioSynthesisDesc& desc);
    static AudioSynthBuffer GenerateBuiltIn(AudioBuiltInSound sound,
                                            std::int32_t sampleRate = 48000);
};

} // namespace Concord::Audio

#endif // CONCORD_AUDIOSYNTH_H
